.pragma library

// What the lock screen says, in the languages below. The explorer itself is
// English; this covers what everyone sees on a locked screen: prompts,
// greetings, failures, status lines. Keys are the English text; a design asks
// for it through `lock.tr("Press Enter to unlock")` and gets it back unchanged
// in English or in a language without that line yet.
//
// A string made of parts ("󰌾  Locked  ·  Esc clears input") is translated a
// part at a time, the icon in front of a part is kept, and a part written in
// capitals or all lowercase comes back the same way, so one entry serves
// "LOCKED", "locked" and "Locked". %1 is filled in by the caller with .arg().
//
// Corrections and new languages are welcome: add a block below, and a line to
// LANGUAGES.

var LANGUAGES = [
  { id: "en", name: "English", locale: "en_US" },
  { id: "da", name: "Dansk", locale: "da_DK" },
  { id: "de", name: "Deutsch", locale: "de_DE" },
  { id: "es", name: "Español", locale: "es_ES" },
  { id: "fr", name: "Français", locale: "fr_FR" },
  { id: "it", name: "Italiano", locale: "it_IT" },
  { id: "nl", name: "Nederlands", locale: "nl_NL" },
  { id: "nb", name: "Norsk", locale: "nb_NO" },
  { id: "pl", name: "Polski", locale: "pl_PL" },
  { id: "pt", name: "Português", locale: "pt_PT" },
  { id: "sv", name: "Svenska", locale: "sv_SE" }
]

var TEXT = {
  da: {
    "Password": "Adgangskode",
    "Type password": "Skriv adgangskode",
    "Enter password": "Indtast adgangskode",
    "Enter your password to unlock": "Indtast din adgangskode for at låse op",
    "Type your password": "Skriv din adgangskode",
    "Type your password or touch the sensor": "Skriv din adgangskode, eller rør sensoren",
    "Press Enter to unlock": "Tryk Enter for at låse op",
    "Enter to unlock": "Enter låser op",
    "Enter unlocks": "Enter låser op",
    "Type to unlock": "Skriv for at låse op",
    "Type to draw": "Skriv for at tegne",
    "Esc clears": "Esc rydder",
    "Esc clears input": "Esc rydder feltet",
    "Esc to clear": "Esc rydder",
    "Ctrl-U clears": "Ctrl-U rydder",
    "Locked": "Låst",
    "Locked, touch sensor or type password": "Låst, rør sensoren eller skriv adgangskode",
    "Checking…": "Kontrollerer…",
    "Touch the sensor or press Enter": "Rør sensoren, eller tryk Enter",
    "Touch sensor or press Enter": "Rør sensoren, eller tryk Enter",
    "Touch sensor or type password": "Rør sensoren, eller skriv adgangskode",
    "Look at sensor or type password": "Kig på sensoren, eller skriv adgangskode",
    "Fingerprint ready": "Fingeraftryk klar",
    "Place your finger": "Læg din finger på",
    "Failed to match fingerprint": "Fingeraftrykket passede ikke",
    "Or touch the reader": "Eller rør læseren",
    "Touch your key": "Rør din nøgle",
    "Touch your key or Tab for password": "Rør din nøgle, eller Tab for adgangskode",
    "Tab for your key": "Tab for din nøgle",
    "Waiting for your key…": "Venter på din nøgle…",
    "Looking for your key…": "Leder efter din nøgle…",
    "No security key found": "Ingen sikkerhedsnøgle fundet",
    "Could not start the key": "Kunne ikke starte nøglen",
    "Enter the PIN for your key": "Indtast PIN-koden til din nøgle",
    "Security key failed (%1)": "Sikkerhedsnøglen fejlede (%1)",
    "Use your password": "Brug din adgangskode",
    "Too many tries": "For mange forsøg",
    "Authentication failed (%1)": "Forkert adgangskode (%1)",
    "Good morning": "Godmorgen",
    "Good afternoon": "God eftermiddag",
    "Good evening": "Godaften",
    "Good night": "Godnat",
    "%1% of the day": "%1% af dagen",
    "Now playing": "Spiller nu",
    "Paused": "På pause",
    "Nothing playing": "Intet spiller",
    "Start something and it shows up here": "Start noget, så vises det her",
    "Loading weather": "Henter vejret",
    "No weather": "Intet vejr",
    "Weather unavailable": "Vejret er ikke tilgængeligt",
    "Today": "I dag",
    "Uptime": "Oppetid",
    "Memory": "Hukommelse",
    "Load": "Belastning",
    "Kernel": "Kerne",
    "Battery": "Batteri",
    "Charging": "Oplader",
    "On battery": "På batteri",
    "No battery": "Intet batteri",
    "Sleep": "Dvale",
    "Restart": "Genstart",
    "Shut down": "Sluk",
    "Battery low (%1%)": "Lavt batteri (%1%)",
    "1 failed attempt": "1 mislykket forsøg",
    "%1 failed attempts": "%1 mislykkede forsøg",
    "1 failed attempt to unlock": "1 mislykket forsøg på at låse op",
    "%1 failed attempts to unlock": "%1 mislykkede forsøg på at låse op",
    "Lock screen": "Låseskærm",
    "While the screen was locked, the last at %1": "Mens skærmen var låst, det seneste kl. %1"
  },
  de: {
    "Password": "Passwort",
    "Type password": "Passwort eingeben",
    "Enter password": "Passwort eingeben",
    "Enter your password to unlock": "Passwort eingeben zum Entsperren",
    "Type your password": "Passwort eingeben",
    "Type your password or touch the sensor": "Passwort eingeben oder Sensor berühren",
    "Press Enter to unlock": "Enter zum Entsperren",
    "Enter to unlock": "Enter entsperrt",
    "Enter unlocks": "Enter entsperrt",
    "Type to unlock": "Tippen zum Entsperren",
    "Type to draw": "Tippen zum Zeichnen",
    "Esc clears": "Esc löscht",
    "Esc clears input": "Esc löscht die Eingabe",
    "Esc to clear": "Esc löscht",
    "Ctrl-U clears": "Strg-U löscht",
    "Locked": "Gesperrt",
    "Locked, touch sensor or type password": "Gesperrt, Sensor berühren oder Passwort eingeben",
    "Checking…": "Wird geprüft…",
    "Touch the sensor or press Enter": "Sensor berühren oder Enter drücken",
    "Touch sensor or press Enter": "Sensor berühren oder Enter drücken",
    "Touch sensor or type password": "Sensor berühren oder Passwort eingeben",
    "Look at sensor or type password": "In den Sensor sehen oder Passwort eingeben",
    "Fingerprint ready": "Fingerabdruck bereit",
    "Place your finger": "Finger auflegen",
    "Failed to match fingerprint": "Fingerabdruck nicht erkannt",
    "Or touch the reader": "Oder den Leser berühren",
    "Touch your key": "Schlüssel berühren",
    "Touch your key or Tab for password": "Schlüssel berühren oder Tab für Passwort",
    "Tab for your key": "Tab für den Schlüssel",
    "Waiting for your key…": "Warte auf den Schlüssel…",
    "Looking for your key…": "Suche den Schlüssel…",
    "No security key found": "Kein Sicherheitsschlüssel gefunden",
    "Could not start the key": "Schlüssel konnte nicht gestartet werden",
    "Enter the PIN for your key": "PIN des Schlüssels eingeben",
    "Security key failed (%1)": "Sicherheitsschlüssel fehlgeschlagen (%1)",
    "Use your password": "Passwort verwenden",
    "Too many tries": "Zu viele Versuche",
    "Authentication failed (%1)": "Anmeldung fehlgeschlagen (%1)",
    "Good morning": "Guten Morgen",
    "Good afternoon": "Guten Tag",
    "Good evening": "Guten Abend",
    "Good night": "Gute Nacht",
    "%1% of the day": "%1 % des Tages",
    "Now playing": "Läuft gerade",
    "Paused": "Pausiert",
    "Nothing playing": "Nichts läuft",
    "Start something and it shows up here": "Starte etwas, dann erscheint es hier",
    "Loading weather": "Wetter wird geladen",
    "No weather": "Kein Wetter",
    "Weather unavailable": "Wetter nicht verfügbar",
    "Today": "Heute",
    "Uptime": "Laufzeit",
    "Memory": "Speicher",
    "Load": "Last",
    "Kernel": "Kernel",
    "Battery": "Akku",
    "Charging": "Lädt",
    "On battery": "Akkubetrieb",
    "No battery": "Kein Akku",
    "Sleep": "Ruhezustand",
    "Restart": "Neu starten",
    "Shut down": "Herunterfahren",
    "Battery low (%1%)": "Akku schwach (%1 %)",
    "1 failed attempt": "1 Fehlversuch",
    "%1 failed attempts": "%1 Fehlversuche",
    "1 failed attempt to unlock": "1 fehlgeschlagener Entsperrversuch",
    "%1 failed attempts to unlock": "%1 fehlgeschlagene Entsperrversuche",
    "Lock screen": "Sperrbildschirm",
    "While the screen was locked, the last at %1": "Während der Bildschirm gesperrt war, zuletzt um %1"
  },
  es: {
    "Password": "Contraseña",
    "Type password": "Escribe la contraseña",
    "Enter password": "Introduce la contraseña",
    "Enter your password to unlock": "Introduce tu contraseña para desbloquear",
    "Type your password": "Escribe tu contraseña",
    "Type your password or touch the sensor": "Escribe tu contraseña o toca el sensor",
    "Press Enter to unlock": "Pulsa Intro para desbloquear",
    "Enter to unlock": "Intro para desbloquear",
    "Enter unlocks": "Intro desbloquea",
    "Type to unlock": "Escribe para desbloquear",
    "Type to draw": "Escribe para dibujar",
    "Esc clears": "Esc borra",
    "Esc clears input": "Esc borra lo escrito",
    "Esc to clear": "Esc para borrar",
    "Ctrl-U clears": "Ctrl-U borra",
    "Locked": "Bloqueado",
    "Locked, touch sensor or type password": "Bloqueado, toca el sensor o escribe la contraseña",
    "Checking…": "Comprobando…",
    "Touch the sensor or press Enter": "Toca el sensor o pulsa Intro",
    "Touch sensor or press Enter": "Toca el sensor o pulsa Intro",
    "Touch sensor or type password": "Toca el sensor o escribe la contraseña",
    "Look at sensor or type password": "Mira al sensor o escribe la contraseña",
    "Fingerprint ready": "Huella lista",
    "Place your finger": "Coloca el dedo",
    "Failed to match fingerprint": "La huella no coincide",
    "Or touch the reader": "O toca el lector",
    "Touch your key": "Toca tu llave",
    "Touch your key or Tab for password": "Toca tu llave o Tab para la contraseña",
    "Tab for your key": "Tab para tu llave",
    "Waiting for your key…": "Esperando tu llave…",
    "Looking for your key…": "Buscando tu llave…",
    "No security key found": "No se encontró ninguna llave de seguridad",
    "Could not start the key": "No se pudo iniciar la llave",
    "Enter the PIN for your key": "Introduce el PIN de tu llave",
    "Security key failed (%1)": "Falló la llave de seguridad (%1)",
    "Use your password": "Usa tu contraseña",
    "Too many tries": "Demasiados intentos",
    "Authentication failed (%1)": "Falló la autenticación (%1)",
    "Good morning": "Buenos días",
    "Good afternoon": "Buenas tardes",
    "Good evening": "Buenas tardes",
    "Good night": "Buenas noches",
    "%1% of the day": "%1 % del día",
    "Now playing": "Reproduciendo",
    "Paused": "En pausa",
    "Nothing playing": "Nada en reproducción",
    "Start something and it shows up here": "Reproduce algo y aparecerá aquí",
    "Loading weather": "Cargando el tiempo",
    "No weather": "Sin datos del tiempo",
    "Weather unavailable": "El tiempo no está disponible",
    "Today": "Hoy",
    "Uptime": "Tiempo activo",
    "Memory": "Memoria",
    "Load": "Carga",
    "Kernel": "Kernel",
    "Battery": "Batería",
    "Charging": "Cargando",
    "On battery": "Con batería",
    "No battery": "Sin batería",
    "Sleep": "Suspender",
    "Restart": "Reiniciar",
    "Shut down": "Apagar",
    "Battery low (%1%)": "Batería baja (%1 %)",
    "1 failed attempt": "1 intento fallido",
    "%1 failed attempts": "%1 intentos fallidos",
    "1 failed attempt to unlock": "1 intento fallido de desbloqueo",
    "%1 failed attempts to unlock": "%1 intentos fallidos de desbloqueo",
    "Lock screen": "Pantalla de bloqueo",
    "While the screen was locked, the last at %1": "Mientras la pantalla estaba bloqueada, el último a las %1"
  },
  fr: {
    "Password": "Mot de passe",
    "Type password": "Saisissez le mot de passe",
    "Enter password": "Saisissez le mot de passe",
    "Enter your password to unlock": "Saisissez votre mot de passe pour déverrouiller",
    "Type your password": "Saisissez votre mot de passe",
    "Type your password or touch the sensor": "Saisissez votre mot de passe ou touchez le capteur",
    "Press Enter to unlock": "Appuyez sur Entrée pour déverrouiller",
    "Enter to unlock": "Entrée pour déverrouiller",
    "Enter unlocks": "Entrée déverrouille",
    "Type to unlock": "Tapez pour déverrouiller",
    "Type to draw": "Tapez pour dessiner",
    "Esc clears": "Échap efface",
    "Esc clears input": "Échap efface la saisie",
    "Esc to clear": "Échap pour effacer",
    "Ctrl-U clears": "Ctrl-U efface",
    "Locked": "Verrouillé",
    "Locked, touch sensor or type password": "Verrouillé, touchez le capteur ou saisissez le mot de passe",
    "Checking…": "Vérification…",
    "Touch the sensor or press Enter": "Touchez le capteur ou appuyez sur Entrée",
    "Touch sensor or press Enter": "Touchez le capteur ou appuyez sur Entrée",
    "Touch sensor or type password": "Touchez le capteur ou saisissez le mot de passe",
    "Look at sensor or type password": "Regardez le capteur ou saisissez le mot de passe",
    "Fingerprint ready": "Empreinte prête",
    "Place your finger": "Posez votre doigt",
    "Failed to match fingerprint": "Empreinte non reconnue",
    "Or touch the reader": "Ou touchez le lecteur",
    "Touch your key": "Touchez votre clé",
    "Touch your key or Tab for password": "Touchez votre clé ou Tab pour le mot de passe",
    "Tab for your key": "Tab pour votre clé",
    "Waiting for your key…": "En attente de votre clé…",
    "Looking for your key…": "Recherche de votre clé…",
    "No security key found": "Aucune clé de sécurité trouvée",
    "Could not start the key": "Impossible de démarrer la clé",
    "Enter the PIN for your key": "Saisissez le code PIN de votre clé",
    "Security key failed (%1)": "Échec de la clé de sécurité (%1)",
    "Use your password": "Utilisez votre mot de passe",
    "Too many tries": "Trop de tentatives",
    "Authentication failed (%1)": "Échec de l’authentification (%1)",
    "Good morning": "Bonjour",
    "Good afternoon": "Bon après-midi",
    "Good evening": "Bonsoir",
    "Good night": "Bonne nuit",
    "%1% of the day": "%1 % de la journée",
    "Now playing": "En cours de lecture",
    "Paused": "En pause",
    "Nothing playing": "Aucune lecture",
    "Start something and it shows up here": "Lancez quelque chose et cela s’affichera ici",
    "Loading weather": "Chargement de la météo",
    "No weather": "Pas de météo",
    "Weather unavailable": "Météo indisponible",
    "Today": "Aujourd’hui",
    "Uptime": "Temps de fonctionnement",
    "Memory": "Mémoire",
    "Load": "Charge",
    "Kernel": "Noyau",
    "Battery": "Batterie",
    "Charging": "En charge",
    "On battery": "Sur batterie",
    "No battery": "Pas de batterie",
    "Sleep": "Veille",
    "Restart": "Redémarrer",
    "Shut down": "Éteindre",
    "Battery low (%1%)": "Batterie faible (%1 %)",
    "1 failed attempt": "1 tentative échouée",
    "%1 failed attempts": "%1 tentatives échouées",
    "1 failed attempt to unlock": "1 tentative de déverrouillage échouée",
    "%1 failed attempts to unlock": "%1 tentatives de déverrouillage échouées",
    "Lock screen": "Écran de verrouillage",
    "While the screen was locked, the last at %1": "Pendant que l’écran était verrouillé, la dernière à %1"
  },
  it: {
    "Password": "Password",
    "Type password": "Digita la password",
    "Enter password": "Inserisci la password",
    "Enter your password to unlock": "Inserisci la password per sbloccare",
    "Type your password": "Digita la password",
    "Type your password or touch the sensor": "Digita la password o tocca il sensore",
    "Press Enter to unlock": "Premi Invio per sbloccare",
    "Enter to unlock": "Invio per sbloccare",
    "Enter unlocks": "Invio sblocca",
    "Type to unlock": "Digita per sbloccare",
    "Type to draw": "Digita per disegnare",
    "Esc clears": "Esc cancella",
    "Esc clears input": "Esc cancella il testo",
    "Esc to clear": "Esc per cancellare",
    "Ctrl-U clears": "Ctrl-U cancella",
    "Locked": "Bloccato",
    "Locked, touch sensor or type password": "Bloccato, tocca il sensore o digita la password",
    "Checking…": "Verifica…",
    "Touch the sensor or press Enter": "Tocca il sensore o premi Invio",
    "Touch sensor or press Enter": "Tocca il sensore o premi Invio",
    "Touch sensor or type password": "Tocca il sensore o digita la password",
    "Look at sensor or type password": "Guarda il sensore o digita la password",
    "Fingerprint ready": "Impronta pronta",
    "Place your finger": "Appoggia il dito",
    "Failed to match fingerprint": "Impronta non riconosciuta",
    "Or touch the reader": "O tocca il lettore",
    "Touch your key": "Tocca la chiave",
    "Touch your key or Tab for password": "Tocca la chiave o Tab per la password",
    "Tab for your key": "Tab per la chiave",
    "Waiting for your key…": "In attesa della chiave…",
    "Looking for your key…": "Ricerca della chiave…",
    "No security key found": "Nessuna chiave di sicurezza trovata",
    "Could not start the key": "Impossibile avviare la chiave",
    "Enter the PIN for your key": "Inserisci il PIN della chiave",
    "Security key failed (%1)": "Chiave di sicurezza non riuscita (%1)",
    "Use your password": "Usa la password",
    "Too many tries": "Troppi tentativi",
    "Authentication failed (%1)": "Autenticazione non riuscita (%1)",
    "Good morning": "Buongiorno",
    "Good afternoon": "Buon pomeriggio",
    "Good evening": "Buonasera",
    "Good night": "Buonanotte",
    "%1% of the day": "%1% della giornata",
    "Now playing": "In riproduzione",
    "Paused": "In pausa",
    "Nothing playing": "Niente in riproduzione",
    "Start something and it shows up here": "Avvia qualcosa e apparirà qui",
    "Loading weather": "Caricamento meteo",
    "No weather": "Nessun meteo",
    "Weather unavailable": "Meteo non disponibile",
    "Today": "Oggi",
    "Uptime": "Tempo di attività",
    "Memory": "Memoria",
    "Load": "Carico",
    "Kernel": "Kernel",
    "Battery": "Batteria",
    "Charging": "In carica",
    "On battery": "A batteria",
    "No battery": "Nessuna batteria",
    "Sleep": "Sospendi",
    "Restart": "Riavvia",
    "Shut down": "Spegni",
    "Battery low (%1%)": "Batteria scarica (%1%)",
    "1 failed attempt": "1 tentativo fallito",
    "%1 failed attempts": "%1 tentativi falliti",
    "1 failed attempt to unlock": "1 tentativo di sblocco non riuscito",
    "%1 failed attempts to unlock": "%1 tentativi di sblocco non riusciti",
    "Lock screen": "Schermata di blocco",
    "While the screen was locked, the last at %1": "Mentre lo schermo era bloccato, l’ultimo alle %1"
  },
  nl: {
    "Password": "Wachtwoord",
    "Type password": "Typ wachtwoord",
    "Enter password": "Voer wachtwoord in",
    "Enter your password to unlock": "Voer je wachtwoord in om te ontgrendelen",
    "Type your password": "Typ je wachtwoord",
    "Type your password or touch the sensor": "Typ je wachtwoord of raak de sensor aan",
    "Press Enter to unlock": "Druk op Enter om te ontgrendelen",
    "Enter to unlock": "Enter ontgrendelt",
    "Enter unlocks": "Enter ontgrendelt",
    "Type to unlock": "Typ om te ontgrendelen",
    "Type to draw": "Typ om te tekenen",
    "Esc clears": "Esc wist",
    "Esc clears input": "Esc wist de invoer",
    "Esc to clear": "Esc om te wissen",
    "Ctrl-U clears": "Ctrl-U wist",
    "Locked": "Vergrendeld",
    "Locked, touch sensor or type password": "Vergrendeld, raak de sensor aan of typ je wachtwoord",
    "Checking…": "Controleren…",
    "Touch the sensor or press Enter": "Raak de sensor aan of druk op Enter",
    "Touch sensor or press Enter": "Raak de sensor aan of druk op Enter",
    "Touch sensor or type password": "Raak de sensor aan of typ je wachtwoord",
    "Look at sensor or type password": "Kijk naar de sensor of typ je wachtwoord",
    "Fingerprint ready": "Vingerafdruk gereed",
    "Place your finger": "Leg je vinger op de lezer",
    "Failed to match fingerprint": "Vingerafdruk niet herkend",
    "Or touch the reader": "Of raak de lezer aan",
    "Touch your key": "Raak je sleutel aan",
    "Touch your key or Tab for password": "Raak je sleutel aan of Tab voor wachtwoord",
    "Tab for your key": "Tab voor je sleutel",
    "Waiting for your key…": "Wachten op je sleutel…",
    "Looking for your key…": "Zoeken naar je sleutel…",
    "No security key found": "Geen beveiligingssleutel gevonden",
    "Could not start the key": "Kan de sleutel niet starten",
    "Enter the PIN for your key": "Voer de pincode van je sleutel in",
    "Security key failed (%1)": "Beveiligingssleutel mislukt (%1)",
    "Use your password": "Gebruik je wachtwoord",
    "Too many tries": "Te veel pogingen",
    "Authentication failed (%1)": "Aanmelden mislukt (%1)",
    "Good morning": "Goedemorgen",
    "Good afternoon": "Goedemiddag",
    "Good evening": "Goedenavond",
    "Good night": "Goedenacht",
    "%1% of the day": "%1% van de dag",
    "Now playing": "Speelt nu",
    "Paused": "Gepauzeerd",
    "Nothing playing": "Er speelt niets",
    "Start something and it shows up here": "Start iets en het verschijnt hier",
    "Loading weather": "Weer laden",
    "No weather": "Geen weer",
    "Weather unavailable": "Weer niet beschikbaar",
    "Today": "Vandaag",
    "Uptime": "Actief",
    "Memory": "Geheugen",
    "Load": "Belasting",
    "Kernel": "Kernel",
    "Battery": "Accu",
    "Charging": "Wordt opgeladen",
    "On battery": "Op accu",
    "No battery": "Geen accu",
    "Sleep": "Slaapstand",
    "Restart": "Herstarten",
    "Shut down": "Afsluiten",
    "Battery low (%1%)": "Accu bijna leeg (%1%)",
    "1 failed attempt": "1 mislukte poging",
    "%1 failed attempts": "%1 mislukte pogingen",
    "1 failed attempt to unlock": "1 mislukte ontgrendelpoging",
    "%1 failed attempts to unlock": "%1 mislukte ontgrendelpogingen",
    "Lock screen": "Vergrendelscherm",
    "While the screen was locked, the last at %1": "Terwijl het scherm vergrendeld was, de laatste om %1"
  },
  nb: {
    "Password": "Passord",
    "Type password": "Skriv passord",
    "Enter password": "Skriv inn passord",
    "Enter your password to unlock": "Skriv inn passordet for å låse opp",
    "Type your password": "Skriv passordet ditt",
    "Type your password or touch the sensor": "Skriv passordet ditt, eller berør sensoren",
    "Press Enter to unlock": "Trykk Enter for å låse opp",
    "Enter to unlock": "Enter låser opp",
    "Enter unlocks": "Enter låser opp",
    "Type to unlock": "Skriv for å låse opp",
    "Type to draw": "Skriv for å tegne",
    "Esc clears": "Esc tømmer",
    "Esc clears input": "Esc tømmer feltet",
    "Esc to clear": "Esc tømmer",
    "Ctrl-U clears": "Ctrl-U tømmer",
    "Locked": "Låst",
    "Locked, touch sensor or type password": "Låst, berør sensoren eller skriv passord",
    "Checking…": "Sjekker…",
    "Touch the sensor or press Enter": "Berør sensoren, eller trykk Enter",
    "Touch sensor or press Enter": "Berør sensoren, eller trykk Enter",
    "Touch sensor or type password": "Berør sensoren, eller skriv passord",
    "Look at sensor or type password": "Se på sensoren, eller skriv passord",
    "Fingerprint ready": "Fingeravtrykk klart",
    "Place your finger": "Legg fingeren på",
    "Failed to match fingerprint": "Fingeravtrykket stemte ikke",
    "Or touch the reader": "Eller berør leseren",
    "Touch your key": "Berør nøkkelen",
    "Touch your key or Tab for password": "Berør nøkkelen, eller Tab for passord",
    "Tab for your key": "Tab for nøkkelen",
    "Waiting for your key…": "Venter på nøkkelen…",
    "Looking for your key…": "Leter etter nøkkelen…",
    "No security key found": "Fant ingen sikkerhetsnøkkel",
    "Could not start the key": "Kunne ikke starte nøkkelen",
    "Enter the PIN for your key": "Skriv inn PIN-koden til nøkkelen",
    "Security key failed (%1)": "Sikkerhetsnøkkelen feilet (%1)",
    "Use your password": "Bruk passordet ditt",
    "Too many tries": "For mange forsøk",
    "Authentication failed (%1)": "Feil passord (%1)",
    "Good morning": "God morgen",
    "Good afternoon": "God ettermiddag",
    "Good evening": "God kveld",
    "Good night": "God natt",
    "%1% of the day": "%1 % av dagen",
    "Now playing": "Spilles nå",
    "Paused": "Pause",
    "Nothing playing": "Ingenting spilles",
    "Start something and it shows up here": "Start noe, så vises det her",
    "Loading weather": "Henter været",
    "No weather": "Ingen værdata",
    "Weather unavailable": "Været er ikke tilgjengelig",
    "Today": "I dag",
    "Uptime": "Oppetid",
    "Memory": "Minne",
    "Load": "Belastning",
    "Kernel": "Kjerne",
    "Battery": "Batteri",
    "Charging": "Lader",
    "On battery": "På batteri",
    "No battery": "Ingen batteri",
    "Sleep": "Hvilemodus",
    "Restart": "Start på nytt",
    "Shut down": "Slå av",
    "Battery low (%1%)": "Lavt batteri (%1 %)",
    "1 failed attempt": "1 mislykket forsøk",
    "%1 failed attempts": "%1 mislykkede forsøk",
    "1 failed attempt to unlock": "1 mislykket forsøk på å låse opp",
    "%1 failed attempts to unlock": "%1 mislykkede forsøk på å låse opp",
    "Lock screen": "Låseskjerm",
    "While the screen was locked, the last at %1": "Mens skjermen var låst, det siste kl. %1"
  },
  pl: {
    "Password": "Hasło",
    "Type password": "Wpisz hasło",
    "Enter password": "Wpisz hasło",
    "Enter your password to unlock": "Wpisz hasło, aby odblokować",
    "Type your password": "Wpisz hasło",
    "Type your password or touch the sensor": "Wpisz hasło lub dotknij czytnika",
    "Press Enter to unlock": "Naciśnij Enter, aby odblokować",
    "Enter to unlock": "Enter odblokowuje",
    "Enter unlocks": "Enter odblokowuje",
    "Type to unlock": "Pisz, aby odblokować",
    "Type to draw": "Pisz, aby rysować",
    "Esc clears": "Esc czyści",
    "Esc clears input": "Esc czyści pole",
    "Esc to clear": "Esc czyści",
    "Ctrl-U clears": "Ctrl-U czyści",
    "Locked": "Zablokowano",
    "Locked, touch sensor or type password": "Zablokowano, dotknij czytnika lub wpisz hasło",
    "Checking…": "Sprawdzanie…",
    "Touch the sensor or press Enter": "Dotknij czytnika lub naciśnij Enter",
    "Touch sensor or press Enter": "Dotknij czytnika lub naciśnij Enter",
    "Touch sensor or type password": "Dotknij czytnika lub wpisz hasło",
    "Look at sensor or type password": "Spójrz w kamerę lub wpisz hasło",
    "Fingerprint ready": "Czytnik gotowy",
    "Place your finger": "Przyłóż palec",
    "Failed to match fingerprint": "Nie rozpoznano odcisku palca",
    "Or touch the reader": "Lub dotknij czytnika",
    "Touch your key": "Dotknij klucza",
    "Touch your key or Tab for password": "Dotknij klucza lub Tab, by wpisać hasło",
    "Tab for your key": "Tab dla klucza",
    "Waiting for your key…": "Czekam na klucz…",
    "Looking for your key…": "Szukam klucza…",
    "No security key found": "Nie znaleziono klucza bezpieczeństwa",
    "Could not start the key": "Nie udało się uruchomić klucza",
    "Enter the PIN for your key": "Wpisz PIN klucza",
    "Security key failed (%1)": "Błąd klucza bezpieczeństwa (%1)",
    "Use your password": "Użyj hasła",
    "Too many tries": "Zbyt wiele prób",
    "Authentication failed (%1)": "Uwierzytelnianie nie powiodło się (%1)",
    "Good morning": "Dzień dobry",
    "Good afternoon": "Dzień dobry",
    "Good evening": "Dobry wieczór",
    "Good night": "Dobranoc",
    "%1% of the day": "%1% dnia",
    "Now playing": "Teraz odtwarzane",
    "Paused": "Wstrzymano",
    "Nothing playing": "Nic nie gra",
    "Start something and it shows up here": "Włącz coś, a pojawi się tutaj",
    "Loading weather": "Wczytywanie pogody",
    "No weather": "Brak pogody",
    "Weather unavailable": "Pogoda niedostępna",
    "Today": "Dziś",
    "Uptime": "Czas pracy",
    "Memory": "Pamięć",
    "Load": "Obciążenie",
    "Kernel": "Jądro",
    "Battery": "Bateria",
    "Charging": "Ładowanie",
    "On battery": "Na baterii",
    "No battery": "Brak baterii",
    "Sleep": "Uśpij",
    "Restart": "Uruchom ponownie",
    "Shut down": "Wyłącz",
    "Battery low (%1%)": "Niski poziom baterii (%1%)",
    "1 failed attempt": "1 nieudana próba",
    "%1 failed attempts": "Nieudane próby: %1",
    "1 failed attempt to unlock": "1 nieudana próba odblokowania",
    "%1 failed attempts to unlock": "Nieudane próby odblokowania: %1",
    "Lock screen": "Ekran blokady",
    "While the screen was locked, the last at %1": "Gdy ekran był zablokowany, ostatnia o %1"
  },
  pt: {
    "Password": "Palavra-passe",
    "Type password": "Escreva a palavra-passe",
    "Enter password": "Introduza a palavra-passe",
    "Enter your password to unlock": "Introduza a palavra-passe para desbloquear",
    "Type your password": "Escreva a sua palavra-passe",
    "Type your password or touch the sensor": "Escreva a palavra-passe ou toque no sensor",
    "Press Enter to unlock": "Prima Enter para desbloquear",
    "Enter to unlock": "Enter desbloqueia",
    "Enter unlocks": "Enter desbloqueia",
    "Type to unlock": "Escreva para desbloquear",
    "Type to draw": "Escreva para desenhar",
    "Esc clears": "Esc limpa",
    "Esc clears input": "Esc limpa o campo",
    "Esc to clear": "Esc para limpar",
    "Ctrl-U clears": "Ctrl-U limpa",
    "Locked": "Bloqueado",
    "Locked, touch sensor or type password": "Bloqueado, toque no sensor ou escreva a palavra-passe",
    "Checking…": "A verificar…",
    "Touch the sensor or press Enter": "Toque no sensor ou prima Enter",
    "Touch sensor or press Enter": "Toque no sensor ou prima Enter",
    "Touch sensor or type password": "Toque no sensor ou escreva a palavra-passe",
    "Look at sensor or type password": "Olhe para o sensor ou escreva a palavra-passe",
    "Fingerprint ready": "Impressão digital pronta",
    "Place your finger": "Coloque o dedo",
    "Failed to match fingerprint": "Impressão digital não reconhecida",
    "Or touch the reader": "Ou toque no leitor",
    "Touch your key": "Toque na chave",
    "Touch your key or Tab for password": "Toque na chave ou Tab para a palavra-passe",
    "Tab for your key": "Tab para a chave",
    "Waiting for your key…": "À espera da chave…",
    "Looking for your key…": "À procura da chave…",
    "No security key found": "Nenhuma chave de segurança encontrada",
    "Could not start the key": "Não foi possível iniciar a chave",
    "Enter the PIN for your key": "Introduza o PIN da chave",
    "Security key failed (%1)": "A chave de segurança falhou (%1)",
    "Use your password": "Use a palavra-passe",
    "Too many tries": "Demasiadas tentativas",
    "Authentication failed (%1)": "A autenticação falhou (%1)",
    "Good morning": "Bom dia",
    "Good afternoon": "Boa tarde",
    "Good evening": "Boa noite",
    "Good night": "Boa noite",
    "%1% of the day": "%1% do dia",
    "Now playing": "A reproduzir",
    "Paused": "Em pausa",
    "Nothing playing": "Nada a reproduzir",
    "Start something and it shows up here": "Reproduza algo e aparece aqui",
    "Loading weather": "A carregar a meteorologia",
    "No weather": "Sem meteorologia",
    "Weather unavailable": "Meteorologia indisponível",
    "Today": "Hoje",
    "Uptime": "Tempo ativo",
    "Memory": "Memória",
    "Load": "Carga",
    "Kernel": "Kernel",
    "Battery": "Bateria",
    "Charging": "A carregar",
    "On battery": "Na bateria",
    "No battery": "Sem bateria",
    "Sleep": "Suspender",
    "Restart": "Reiniciar",
    "Shut down": "Encerrar",
    "Battery low (%1%)": "Bateria fraca (%1%)",
    "1 failed attempt": "1 tentativa falhada",
    "%1 failed attempts": "%1 tentativas falhadas",
    "1 failed attempt to unlock": "1 tentativa de desbloqueio falhada",
    "%1 failed attempts to unlock": "%1 tentativas de desbloqueio falhadas",
    "Lock screen": "Ecrã de bloqueio",
    "While the screen was locked, the last at %1": "Enquanto o ecrã estava bloqueado, a última às %1"
  },
  sv: {
    "Password": "Lösenord",
    "Type password": "Skriv lösenord",
    "Enter password": "Ange lösenord",
    "Enter your password to unlock": "Ange ditt lösenord för att låsa upp",
    "Type your password": "Skriv ditt lösenord",
    "Type your password or touch the sensor": "Skriv ditt lösenord eller rör vid sensorn",
    "Press Enter to unlock": "Tryck Enter för att låsa upp",
    "Enter to unlock": "Enter låser upp",
    "Enter unlocks": "Enter låser upp",
    "Type to unlock": "Skriv för att låsa upp",
    "Type to draw": "Skriv för att rita",
    "Esc clears": "Esc rensar",
    "Esc clears input": "Esc rensar fältet",
    "Esc to clear": "Esc rensar",
    "Ctrl-U clears": "Ctrl-U rensar",
    "Locked": "Låst",
    "Locked, touch sensor or type password": "Låst, rör vid sensorn eller skriv lösenord",
    "Checking…": "Kontrollerar…",
    "Touch the sensor or press Enter": "Rör vid sensorn eller tryck Enter",
    "Touch sensor or press Enter": "Rör vid sensorn eller tryck Enter",
    "Touch sensor or type password": "Rör vid sensorn eller skriv lösenord",
    "Look at sensor or type password": "Titta på sensorn eller skriv lösenord",
    "Fingerprint ready": "Fingeravtryck redo",
    "Place your finger": "Placera fingret",
    "Failed to match fingerprint": "Fingeravtrycket matchade inte",
    "Or touch the reader": "Eller rör vid läsaren",
    "Touch your key": "Rör vid nyckeln",
    "Touch your key or Tab for password": "Rör vid nyckeln eller Tab för lösenord",
    "Tab for your key": "Tab för nyckeln",
    "Waiting for your key…": "Väntar på nyckeln…",
    "Looking for your key…": "Letar efter nyckeln…",
    "No security key found": "Ingen säkerhetsnyckel hittades",
    "Could not start the key": "Kunde inte starta nyckeln",
    "Enter the PIN for your key": "Ange PIN-koden för nyckeln",
    "Security key failed (%1)": "Säkerhetsnyckeln misslyckades (%1)",
    "Use your password": "Använd ditt lösenord",
    "Too many tries": "För många försök",
    "Authentication failed (%1)": "Fel lösenord (%1)",
    "Good morning": "God morgon",
    "Good afternoon": "God eftermiddag",
    "Good evening": "God kväll",
    "Good night": "God natt",
    "%1% of the day": "%1 % av dagen",
    "Now playing": "Spelas nu",
    "Paused": "Pausad",
    "Nothing playing": "Inget spelas",
    "Start something and it shows up here": "Starta något så visas det här",
    "Loading weather": "Hämtar vädret",
    "No weather": "Inget väder",
    "Weather unavailable": "Vädret är inte tillgängligt",
    "Today": "I dag",
    "Uptime": "Drifttid",
    "Memory": "Minne",
    "Load": "Belastning",
    "Kernel": "Kärna",
    "Battery": "Batteri",
    "Charging": "Laddar",
    "On battery": "På batteri",
    "No battery": "Inget batteri",
    "Sleep": "Vila",
    "Restart": "Starta om",
    "Shut down": "Stäng av",
    "Battery low (%1%)": "Låg batterinivå (%1 %)",
    "1 failed attempt": "1 misslyckat försök",
    "%1 failed attempts": "%1 misslyckade försök",
    "1 failed attempt to unlock": "1 misslyckat upplåsningsförsök",
    "%1 failed attempts to unlock": "%1 misslyckade upplåsningsförsök",
    "Lock screen": "Låsskärm",
    "While the screen was locked, the last at %1": "Medan skärmen var låst, det senaste kl. %1"
  }
}

// Lowercased keys, built once, remembering how the English was written.
// ExplorerStrings.js builds its own table the same way.
function makeLookup(text) {
  var out = {}
  for (var lang in text) {
    out[lang] = {}
    for (var key in text[lang]) out[lang][key.toLowerCase()] = { key: key, text: text[lang][key] }
  }
  return out
}
var LOOKUP = makeLookup(TEXT)

function known(id) {
  for (var i = 0; i < LANGUAGES.length; i++) if (LANGUAGES[i].id === id) return true
  return false
}

// "de_DE.UTF-8", "pt_BR", "nn_NO" -> a language this file has, or "en".
function fromLocale(name) {
  var code = String(name || "").toLowerCase().split(/[_.@-]/)[0]
  if (code === "no" || code === "nn") code = "nb"
  return known(code) ? code : "en"
}

function localeName(id) {
  for (var i = 0; i < LANGUAGES.length; i++) if (LANGUAGES[i].id === id) return LANGUAGES[i].locale
  return "en_US"
}

function piece(table, part) {
  // Whatever stands in front of the words (an icon, spaces) is kept as is.
  var m = /^([^A-Za-zÀ-ÿ0-9%]*)([\s\S]*?)(\s*)$/.exec(part)
  var core = m ? m[2] : ""
  if (core.length === 0) return null
  var hit = table[core.toLowerCase()]
  if (hit === undefined) return null
  var text = hit.text
  // Written the way the English entry is: as translated. Otherwise the
  // design chose capitals or lowercase for the look, and gets them.
  if (core !== hit.key) {
    if (core === core.toUpperCase() && core !== core.toLowerCase()) text = text.toUpperCase()
    else if (core === core.toLowerCase() && core !== core.toUpperCase()) text = text.toLowerCase()
  }
  return m[1] + text + m[3]
}

function tr(lang, text) {
  return trWith(LOOKUP, lang, text)
}

function trWith(lookup, lang, text) {
  var s = String(text === undefined || text === null ? "" : text)
  var table = lookup[lang]
  if (!table || s.length === 0) return s
  var whole = piece(table, s)
  if (whole !== null) return whole
  var parts = s.split(/(\s+·\s+)/)
  if (parts.length === 1) return s
  for (var i = 0; i < parts.length; i += 2) {
    var t = piece(table, parts[i])
    if (t !== null) parts[i] = t
  }
  return parts.join("")
}
