#!/bin/bash
# Shared generator for the clip designs (Storm, Eyes, Rally, River): the
# clip's first frame is the boot screen and the rest of it plays as a frame
# sequence when the passphrase checks out, the same deal as the QML
# ClipDesign. Frames are preloaded by the theme script because switch_root
# wipes the initramfs from RAM right after the unlock.
#
# Usage (from a design's generate.sh): cliptwin.sh <staging> <design-id> <clip-file>
set -euo pipefail
source "$(dirname "$(realpath "$0")")/common.sh"

staging="${1:?usage: cliptwin.sh <staging-dir> <design-id> <clip-file>}"
design="${2:?missing design id}"
clip="$HOME/.config/omarchy/lock-videos/${3:?missing clip filename}"

if [[ ! -f $clip ]]; then
  echo "Missing $clip - drop the design's video in ~/.config/omarchy/lock-videos first" >&2
  exit 1
fi

mkdir -p "$staging"

bg=$(theme_color background)
fg=$(theme_color foreground)
dim=$(mix_hex 888888 ffffff 0.3)
family=$(mono_font_family)

fg_f=$(hex_floats "$fg"); dim_f=$(hex_floats "$dim"); bg_i=$(hex_ints "$bg"); fg_i=$(hex_ints "$fg")

# Render frames at the panel's native resolution when we can see it.
res=$(hyprctl monitors -j 2>/dev/null | python3 -c "
import json, sys
try:
    m = json.load(sys.stdin)[0]
    print(m['width'], m['height'])
except Exception:
    print('1920 1080')
" 2>/dev/null || echo "1920 1080")
w=${res%% *}; h=${res##* }

# Preview mode stops after the thumbnail: one frame instead of the whole
# sequence, so the explorer can render its cards quickly.
if [[ ${PREVIEW_ONLY:-0} == 1 ]]; then
  ffmpeg -v error -y -i "$clip" -vf "scale=720:405:force_original_aspect_ratio=increase,crop=720:405" -frames:v 1 "$staging/first.png"
  magick -size 220x30 xc:none -draw "fill rgba($bg_i,0.55) roundrectangle 0,0 219,29 15,15" "$staging/pill-s.png"
  magick "$staging/first.png" \
    \( -size 720x101 gradient:'#00000073-#00000000' \) -geometry +0+0 -composite \
    \( -size 720x121 gradient:'#00000000-#00000080' \) -geometry +0+284 -composite \
    "$staging/pill-s.png" -gravity south -geometry +0+18 -composite \
    "$staging/preview.png"
  exit 0
fi

# Whole clip by default, capped at 72 frames: drop the frame rate for longer
# clips rather than cutting them short. BOOT_CLIP_SECONDS trims the clip to
# the first N seconds instead (0 or unset plays it all).
duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$clip")
limit="${BOOT_CLIP_SECONDS:-0}"
if awk -v l="$limit" -v d="$duration" 'BEGIN { exit !(l > 0 && l < d) }'; then
  duration=$limit
fi
fps=$(awk -v d="$duration" 'BEGIN { f = 72 / d; if (f > 12) f = 12; printf "%.3f", f }')

ffmpeg -v error -y -t "$duration" -i "$clip" -vf "fps=$fps,scale=$w:$h:force_original_aspect_ratio=increase,crop=$w:$h" \
  -start_number 0 "$staging/fr%02d.png"
num_frames=$(ls "$staging"/fr*.png | wc -l)

# The still: first frame with the ClipDesign scrims baked in.
magick "$staging/fr00.png" \
  \( -size "${w}x$((h / 4))" gradient:'#00000073-#00000000' \) -geometry +0+0 -composite \
  \( -size "${w}x$((h * 3 / 10))" gradient:'#00000000-#00000080' \) -geometry "+0+$((h - h * 3 / 10))" -composite \
  "$staging/still.png"

magick -size 400x56 xc:none -draw "fill rgba($bg_i,0.55) roundrectangle 0,0 399,55 28,28" "$staging/pill.png"
magick -size 14x14 xc:none -fill "rgba($fg_i,0.95)" -draw "circle 7,7 7,2" "$staging/dot.png"

write_theme_ini "$staging" "$bg" "$family"
echo "$design" > "$staging/design"

# Thumbnail for the explorer's boot panel: the still with the pill on it.
magick "$staging/still.png" -resize 720x405^ -gravity center -extent 720x405 \
  \( "$staging/pill.png" -resize x34 \) -gravity south -geometry +0+30 -composite \
  "$staging/preview.png"

cat > "$staging/omarchy-boot.script" <<EOF
# Clip design twin ($design), generated by omarchy-lock-explorer.
# First frame is the lock, the rest plays when you unlock.

fg.r = ${fg_f%%,*}; fg.g = $(echo "$fg_f" | cut -d, -f2); fg.b = $(echo "$fg_f" | cut -d, -f3);
dim.r = ${dim_f%%,*}; dim.g = $(echo "$dim_f" | cut -d, -f2); dim.b = $(echo "$dim_f" | cut -d, -f3);

font.body = "$family 15";
font.small = "$family 12";

clip.fps = $fps;
num_frames = $num_frames;

Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

# Every head measured on its own and moved to a slice of the canvas of its
# own, as in the custom generator: Plymouth centres the heads on each other,
# so a single Window.GetWidth() layout or one shared sprite lands on a head of
# another shape stretched or cut off (issue #38). The room between the slices
# keeps a clip filled past one head's edges off the next.
display_count = 0;
next_x = 0;
i = 0;
while (i < 8) {
  dw = Window.GetWidth(i);
  dh = Window.GetHeight(i);
  if (dw > 0) {
    Window.SetX(i, next_x);
    Window.SetY(i, 0);
    dsp_i[display_count] = i;
    dsp_x[display_count] = next_x;
    dsp_y[display_count] = 0;
    dsp_w[display_count] = dw;
    dsp_h[display_count] = dh;
    display_count++;
    next_x = next_x + dw + 32768;
  }
  i++;
}
moved_count = display_count;
# An older plymouth that does not take a display index answers for the one
# screen it has; that is the single-head case and it still works.
if (display_count == 0) {
  dsp_x[0] = 0;
  dsp_y[0] = 0;
  dsp_w[0] = Window.GetWidth();
  dsp_h[0] = Window.GetHeight();
  display_count = 1;
}

# Plymouth centres the heads on each other again after every prompt, message
# and keystroke (script_lib_update_displays in plugin.c), which would pull the
# layout above back into the overlap. The refresh puts each head back in its
# slice; Window.SetX/SetY only redraw when a position actually changes.
fun place_heads() {
  d = 0;
  while (d < moved_count) {
    Window.SetX(dsp_i[d], dsp_x[d]);
    Window.SetY(dsp_i[d], dsp_y[d]);
    d++;
  }
}

# The entry and the messages live on the first head; the others carry the
# clip alone.
screen.x = dsp_x[0];
screen.y = dsp_y[0];
screen.w = dsp_w[0];
screen.h = dsp_h[0];

# Per head: the frames were rendered at the session monitor's size, which need
# not be this head's. One scale factor for both axes, filling the head, the
# leftover centred off its edges -- scaling each axis to the screen
# independently stretched the clip on any head of a different shape.
i = 0;
while (i < display_count) {
  s = dsp_w[i] / $w;
  if (dsp_h[i] / $h > s) s = dsp_h[i] / $h;
  clip_w[i] = Math.Int($w * s);
  clip_h[i] = Math.Int($h * s);
  clip_x[i] = dsp_x[i] + (dsp_w[i] - clip_w[i]) / 2;
  clip_y[i] = dsp_y[i] + (dsp_h[i] - clip_h[i]) / 2;
  i++;
}

# The frame for head d: the preloaded one, sized for the first head, or a copy
# scaled for a head of another size.
fun clip_frame(image, d) {
  if (clip_w[d] == clip_w[0] && clip_h[d] == clip_h[0]) return image;
  return image.Scale(clip_w[d], clip_h[d]);
}

digits = "0123456789";

fun frame_name(i) {
  d1 = Math.Int(i / 10);
  return "fr" + digits.CharAt(d1) + digits.CharAt(i - d1 * 10) + ".png";
}

still.image = Image("still.png");
if (clip_w[0] != $w || clip_h[0] != $h) still.image = still.image.Scale(clip_w[0], clip_h[0]);
i = 0;
while (i < display_count) {
  still_sprites[i] = Sprite(clip_frame(still.image, i));
  still_sprites[i].SetPosition(clip_x[i], clip_y[i], 1);
  i++;
}

fun show_frame(image) {
  i = 0;
  while (i < display_count) {
    still_sprites[i].SetImage(clip_frame(image, i));
    i++;
  }
}

# The clip only ever plays after a passphrase prompt on the way up; during
# reboot/shutdown plymouthd runs this theme too, and decoding the whole
# sequence there would waste the shutdown on frames never shown.
$(emit_downward_gate boot_like)

if (global.boot_like == 1) {
  for (i = 0; i < num_frames; i++) {
    frames[i] = Image(frame_name(i));
    if (clip_w[0] != $w || clip_h[0] != $h) frames[i] = frames[i].Scale(clip_w[0], clip_h[0]);
  }
}

#----------------------------------------- Chrome --------------------------------

pill.image = Image("pill.png");
pill.sprite = Sprite(pill.image);
pill.x = screen.x + screen.w / 2 - pill.image.GetWidth() / 2;
pill.y = screen.y + screen.h * 0.93 - 10 - pill.image.GetHeight();
pill.sprite.SetPosition(pill.x, pill.y, 10);

placeholder.image = Image.Text("Password", dim.r, dim.g, dim.b, 1, font.body);
placeholder.sprite = Sprite(placeholder.image);
placeholder.x = pill.x + 24;
placeholder.y = pill.y + pill.image.GetHeight() / 2 - placeholder.image.GetHeight() / 2;
placeholder.sprite.SetPosition(placeholder.x, placeholder.y, 11);

bullet.image = Image("dot.png");
for (i = 0; i < 24; i++) {
  bullets[i] = Sprite();
  bullets[i].SetOpacity(0);
}

fun hide_bullets() {
  for (i = 0; i < 24; i++) bullets[i].SetOpacity(0);
}

global.password_shown = 0;
global.playing = 0;
global.tick = 0;
global.cur_frame = -1;

fun set_chrome_opacity(op) {
  pill.sprite.SetOpacity(op);
  placeholder.sprite.SetOpacity(op);
  if (op == 0) hide_bullets();
}

# Hidden until a passphrase prompt actually fires: plymouthd runs this theme
# for reboot/shutdown too (and for unencrypted boots), where a visible entry
# reads as a prompt that will never accept input.
set_chrome_opacity(0);

fun display_password_callback(prompt_text, count) {
  global.password_shown = 1;

  if (global.playing == 1) {
    # The clip starts on submit, not on success: a prompt firing again means
    # the passphrase was wrong. Rewind to the still and bring the entry back.
    global.playing = 0;
    global.tick = 0;
    global.cur_frame = -1;
    show_frame(still.image);
  }
  set_chrome_opacity(1);

  if (count > 24) count = 24;

  step = bullet.image.GetWidth() + 8;
  cy = pill.y + pill.image.GetHeight() / 2;
  for (i = 0; i < 24; i++) {
    if (i < count) {
      bullets[i].SetImage(bullet.image);
      bullets[i].SetPosition(placeholder.x + i * step, cy - bullet.image.GetHeight() / 2, 11);
      bullets[i].SetOpacity(1);
    } else {
      bullets[i].SetOpacity(0);
    }
  }
  if (count > 0) placeholder.sprite.SetOpacity(0);
  else placeholder.sprite.SetOpacity(1);
}

fun display_normal_callback() {
  if (global.password_shown == 1 && global.playing == 0) {
    # Outside boot the frames were never loaded, so a submitted answer just
    # drops the chrome and keeps the still.
    if (global.boot_like == 1) {
      global.playing = 1;
      global.tick = 0;
    }
    set_chrome_opacity(0);
  }
}

fun refresh_callback() {
  place_heads();
  if (global.playing == 1) {
    global.tick++;
    f = Math.Int(global.tick * clip.fps / 50);
    if (f >= num_frames) f = num_frames - 1;
    if (f != global.cur_frame) {
      global.cur_frame = f;
      show_frame(frames[f]);
    }
  }
}

message_sprite = Sprite();
message_sprite.SetPosition(screen.x + 20, screen.y + screen.h - 30, 12);

fun display_message_callback(text) {
  message_sprite.SetImage(Image.Text(text, dim.r, dim.g, dim.b, 1, font.small));
  message_sprite.SetOpacity(1);
}

fun hide_message_callback(text) {
  message_sprite.SetOpacity(0);
}

Plymouth.SetDisplayPasswordFunction(display_password_callback);
Plymouth.SetDisplayNormalFunction(display_normal_callback);
Plymouth.SetRefreshFunction(refresh_callback);
Plymouth.SetDisplayMessageFunction(display_message_callback);
Plymouth.SetHideMessageFunction(hide_message_callback);
EOF
